class Route:
    task = "/api/task/%d/"
    rerun_config = "/api/task/?filter_by=rerun_key&rerun_key=%s"
    publish_project = "/api/project/%s/publish/"
    add_tasks = "/api/project/%s/add-data/"
    task_results = "/api/task-worker/list-submissions/?task_id=%d"
    task_worker_results = "/api/task-worker/%d/"
    update_task_status = "/api/task-worker/bulk-update-status/"
    task_status = "/api/task/%s/is-done/"
    mock_results = "/api/task-worker-result/mock-results/"
    peer_review = "/api/task/peer-review/"
    true_skill_score = "/api/worker-requester-rating/trueskill/?match_group_id={}"
    boomerang_rating = "/api/worker-requester-rating/boomerang-feedback/"
    subscribe = "/ws/bot?subscribe-user"
